#!/bin/bash
# Script to restart the node server for the group chat
# author: Daniel Mois

echo "Restarting the group chat forever";
 date +"%A, %B %-d, %Y";

echo "Stopping the chat server";
pkill node;

echo "Waiting 5 seconds";
sleep 5s;

echo "Starting the server again";
 cd /home/cyberhus/devel/opeka_kramchat/nodejs;
 forever -a -l chat.log -e err.log -o out.log main.js;
